#!/bin/bash

redshift -l -33.45694:-70.64827 -t 5700:2600 -b 1.0:0.7 -g 0.9 -m randr -v &
xset r rate 300 50 &
setxkbmap -layout us -variant intl -option caps:super,altwin:menu_win &
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
xset -q | grep -q "Caps Lock:\s*on" && xdotool key Caps_Lock
unclutter &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
slstatus &
xwallpaper --zoom /home/lucas/.src/gentoofiles/cpu.jpg &
syncthing &
